import { Connection } from "typeorm";
import { Country } from "./country.entity";

const COUNTRY_LIST = [
    {id: "AFG", name: "Afghanistan"},
    {id: "ALB", name: "Albania"},
    {id: "DZA", name: "Algeria"},
    {id: "AND", name: "Andorra"},
    {id: "AGO", name: "Angola"},
    {id: "ATG", name: "Antigua and Barbuda"},
    {id: "ARG", name: "Argentina"},
    {id: "ARM", name: "Armenia"},
    {id: "AUS", name: "Australia"},
    {id: "AUT", name: "Austria"},
    {id: "AZE", name: "Azerbaijan"},
    {id: "BHS", name: "Bahamas"},
    {id: "BHR", name: "Bahrain"},
    {id: "BGD", name: "Bangladesh"},
    {id: "BRB", name: "Barbados"},
    {id: "BLR", name: "Belarus"},
    {id: "BEL", name: "Belgium"},
    {id: "BLZ", name: "Belize"},
    {id: "BEN", name: "Benin"},
    {id: "BTN", name: "Bhutan"},
    {id: "BOL", name: "Bolivia"},
    {id: "BIH", name: "Bosnia and Herzegovina"},
    {id: "BWA", name: "Botswana"},
    {id: "BRA", name: "Brazil"},
    {id: "BRN", name: "Brunei"},
    {id: "BGR", name: "Bulgaria"},
    {id: "BFA", name: "Burkina Faso"},
    {id: "BDI", name: "Burundi"},
    {id: "CPV", name: "Cabo Verde"},
    {id: "KHM", name: "Cambodia"},
    {id: "CMR", name: "Cameroon"},
    {id: "CAN", name: "Canada"},
    {id: "CAF", name: "Central African Republic"},
    {id: "TCD", name: "Chad"},
    {id: "CHL", name: "Chile"},
    {id: "CHN", name: "China"},
    {id: "COL", name: "Colombia"},
    {id: "COM", name: "Comoros"},
    {id: "COG", name: "Congo (Congo-Brazzaville)"},
    {id: "CRI", name: "Costa Rica"},
    {id: "HRV", name: "Croatia"},
    {id: "CUB", name: "Cuba"},
    {id: "CYP", name: "Cyprus"},
    {id: "CZE", name: "Czechia (Czech Republic)"},
    {id: "COD", name: "Democratic Republic of the Congo"},
    {id: "DNK", name: "Denmark"},
    {id: "DJI", name: "Djibouti"},
    {id: "DMA", name: "Dominica"},
    {id: "DOM", name: "Dominican Republic"},
    {id: "ECU", name: "Ecuador"},
    {id: "EGY", name: "Egypt"},
    {id: "SLV", name: "El Salvador"},
    {id: "GNQ", name: "Equatorial Guinea"},
    {id: "ERI", name: "Eritrea"},
    {id: "EST", name: "Estonia"},
    {id: "SWZ", name: "Eswatini"},
    {id: "ETH", name: "Ethiopia"},
    {id: "FJI", name: "Fiji"},
    {id: "FIN", name: "Finland"},
    {id: "FRA", name: "France"},
    {id: "GAB", name: "Gabon"},
    {id: "GMB", name: "Gambia"},
    {id: "GEO", name: "Georgia"},
    {id: "DEU", name: "Germany"},
    {id: "GHA", name: "Ghana"},
    {id: "GRC", name: "Greece"},
    {id: "GRD", name: "Grenada"},
    {id: "GTM", name: "Guatemala"},
    {id: "GIN", name: "Guinea"},
    {id: "GNB", name: "Guinea-Bissau"},
    {id: "GUY", name: "Guyana"},
    {id: "HTI", name: "Haiti"},
    {id: "HND", name: "Honduras"},
    {id: "HUN", name: "Hungary"},
    {id: "ISL", name: "Iceland"},
    {id: "IND", name: "India"},
    {id: "IDN", name: "Indonesia"},
    {id: "IRN", name: "Iran"},
    {id: "IRQ", name: "Iraq"},
    {id: "IRL", name: "Ireland"},
    {id: "ISR", name: "Israel"},
    {id: "ITA", name: "Italy"},
    {id: "JAM", name: "Jamaica"},
    {id: "JPN", name: "Japan"},
    {id: "JOR", name: "Jordan"},
    {id: "KAZ", name: "Kazakhstan"},
    {id: "KEN", name: "Kenya"},
    {id: "KIR", name: "Kiribati"},
    {id: "KWT", name: "Kuwait"},
    {id: "KGZ", name: "Kyrgyzstan"},
    {id: "LAO", name: "Laos"},
    {id: "LVA", name: "Latvia"},
    {id: "LBN", name: "Lebanon"},
    {id: "LSO", name: "Lesotho"},
    {id: "LBR", name: "Liberia"},
    {id: "LBY", name: "Libya"},
    {id: "LIE", name: "Liechtenstein"},
    {id: "LTU", name: "Lithuania"},
    {id: "LUX", name: "Luxembourg"},
    {id: "MDG", name: "Madagascar"},
    {id: "MWI", name: "Malawi"},
    {id: "MYS", name: "Malaysia"},
    {id: "MDV", name: "Maldives"},
    {id: "MLI", name: "Mali"},
    {id: "MLT", name: "Malta"},
    {id: "MHL", name: "Marshall Islands"},
    {id: "MRT", name: "Mauritania"},
    {id: "MUS", name: "Mauritius"},
    {id: "MEX", name: "Mexico"},
    {id: "FSM", name: "Micronesia"},
    {id: "MDA", name: "Moldova"},
    {id: "MCO", name: "Monaco"},
    {id: "MNG", name: "Mongolia"},
    {id: "MNE", name: "Montenegro"},
    {id: "MAR", name: "Morocco"},
    {id: "MOZ", name: "Mozambique"},
    {id: "MMR", name: "Myanmar (formerly Burma)"},
    {id: "NAM", name: "Namibia"},
    {id: "NRU", name: "Nauru"},
    {id: "NPL", name: "Nepal"},
    {id: "NLD", name: "Netherlands"},
    {id: "NZL", name: "New Zealand"},
    {id: "NIC", name: "Nicaragua"},
    {id: "NER", name: "Niger"},
    {id: "NGA", name: "Nigeria"},
    {id: "MKD", name: "North Macedonia"},
    {id: "NOR", name: "Norway"},
    {id: "OMN", name: "Oman"},
    {id: "PAK", name: "Pakistan"},
    {id: "PLW", name: "Palau"},
    {id: "PSE", name: "Palestine State"},
    {id: "PAN", name: "Panama"},
    {id: "PNG", name: "Papua New Guinea"},
    {id: "PRY", name: "Paraguay"},
    {id: "PER", name: "Peru"},
    {id: "PHL", name: "Philippines"},
    {id: "POL", name: "Poland"},
    {id: "PRT", name: "Portugal"},
    {id: "QAT", name: "Qatar"},
    {id: "ROU", name: "Romania"},
    {id: "RUS", name: "Russia"},
    {id: "RWA", name: "Rwanda"},
    {id: "KNA", name: "Saint Kitts and Nevis"},
    {id: "LCA", name: "Saint Lucia"},
    {id: "VCT", name: "Saint Vincent and the Grenadines"},
    {id: "WSM", name: "Samoa"},
    {id: "SMR", name: "San Marino"},
    {id: "STP", name: "Sao Tome and Principe"},
    {id: "SAU", name: "Saudi Arabia"},
    {id: "SEN", name: "Senegal"},
    {id: "SRB", name: "Serbia"},
    {id: "SYC", name: "Seychelles"},
    {id: "SLE", name: "Sierra Leone"},
    {id: "SGP", name: "Singapore"},
    {id: "SVK", name: "Slovakia"},
    {id: "SVN", name: "Slovenia"},
    {id: "SLB", name: "Solomon Islands"},
    {id: "SOM", name: "Somalia"},
    {id: "ZAF", name: "South Africa"},
    {id: "KOR", name: "South Korea"},
    {id: "SSD", name: "South Sudan"},
    {id: "ESP", name: "Spain"},
    {id: "LKA", name: "Sri Lanka"},
    {id: "SDN", name: "Sudan"},
    {id: "SUR", name: "Suriname"},
    {id: "SWE", name: "Sweden"},
    {id: "CHE", name: "Switzerland"},
    {id: "SYR", name: "Syria"},
    {id: "TWN", name: "Taiwan"},
    {id: "TJK", name: "Tajikistan"},
    {id: "TZA", name: "Tanzania"},
    {id: "THA", name: "Thailand"},
    {id: "TLS", name: "Timor-Leste"},
    {id: "TGO", name: "Togo"},
    {id: "TON", name: "Tonga"},
    {id: "TTO", name: "Trinidad and Tobago"},
    {id: "TUN", name: "Tunisia"},
    {id: "TUR", name: "Turkey"},
    {id: "TKM", name: "Turkmenistan"},
    {id: "TUV", name: "Tuvalu"},
    {id: "UGA", name: "Uganda"},
    {id: "UKR", name: "Ukraine"},
    {id: "ARE", name: "United Arab Emirates"},
    {id: "GBR", name: "United Kingdom"},
    {id: "USA", name: "United States of America"},
    {id: "URY", name: "Uruguay"},
    {id: "UZB", name: "Uzbekistan"},
    {id: "VUT", name: "Vanuatu"},
    {id: "VAT", name: "Vatican City"},
    {id: "VEN", name: "Venezuela"},
    {id: "VNM", name: "Vietnam"},
    {id: "YEM", name: "Yemen"},
    {id: "ZMB", name: "Zambia"},
    {id: "ZWE", name: "Zimbabwe"}
];

async function seedCountry(connection: Connection){
    const countryRepo = connection.getRepository(Country);

    // Do not add countries if they already exist
    const existingCountries = await countryRepo.find();
    const existingCountryCodes = new Set(existingCountries.map(country => country.id));
    
    //exclude existing countries
    const filteredCountries = COUNTRY_LIST.filter(country => !existingCountryCodes.has(country.id));

    if (filteredCountries.length > 0) {
        // Add new countries
        await countryRepo.save(filteredCountries);
        console.log(`${filteredCountries.length} new countries have been seeded.`);
    } else {
        console.log('No new countries to seed.');
    }

}

export default seedCountry;
